package ffmpeg

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// integrationSample holds the path to the generated sample MP4 used by integration tests.
// It is set by TestMain when ffmpeg is available, and empty otherwise.
var integrationSample string

// TestMain generates a valid MP4 sample using ffmpeg before running the test suite.
// If ffmpeg is not available the sample is not generated and integration tests skip themselves.
func TestMain(m *testing.M) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		// ffmpeg not available – run tests as-is; integration test will skip.
		os.Exit(m.Run())
	}

	tmp, err := os.MkdirTemp("", "stereoctl-integration-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "TestMain: failed to create temp dir: %v\n", err)
		os.Exit(1)
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	integrationSample = filepath.Join(tmp, "sample.mp4")
	cmd := exec.Command("ffmpeg", "-y",
		"-f", "lavfi", "-i", "testsrc=duration=5:size=640x360:rate=30",
		"-f", "lavfi", "-i", "sine=frequency=1000:duration=5",
		"-c:v", "libx264", "-pix_fmt", "yuv420p",
		"-c:a", "aac", "-b:a", "128k", "-ac", "2",
		"-shortest",
		integrationSample,
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		fmt.Fprintf(os.Stderr, "TestMain: failed to generate integration sample: %v\n%s\n", err, out)
		os.Exit(1)
	}

	os.Exit(m.Run())
}

// TestConvertIntegration runs a full Probe → Convert cycle against a real MP4 generated by TestMain.
func TestConvertIntegration(t *testing.T) {
	if integrationSample == "" {
		t.Skip("ffmpeg not found, skipping integration test")
	}

	p, err := Probe(integrationSample)
	if err != nil {
		t.Fatalf("ffprobe failed for integration sample: %v", err)
	}

	var copyAudio bool
	var codec string
	var channels int
	for _, s := range p.Streams {
		if s.CodecType == "audio" {
			codec = s.CodecName
			channels = s.Channels
			break
		}
	}
	if codec == "aac" && channels <= 2 {
		copyAudio = true
	}

	out := filepath.Join(os.TempDir(), "stereoctl_test_output.mp4")
	defer func() { _ = os.Remove(out) }()

	opts := ConvertOptions{
		Input:      integrationSample,
		Output:     out,
		CopyAudio:  copyAudio,
		AudioCodec: "aac",
		Channels:   2,
		Bitrate:    "192k",
	}

	if err := Convert(opts, p.Format.Duration); err != nil {
		t.Fatalf("Convert failed: %v", err)
	}

	if _, err := os.Stat(out); err != nil {
		t.Fatalf("expected output file, stat failed: %v", err)
	}
}
